import os
import json
import re
from database.db_manager import DBManager

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

class NumberedCanvas(canvas.Canvas):
    """Custom canvas to implement two-pass page numbering (Page X of Y)."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#4A5568"))
        
        # Don't draw headers/footers on the cover page
        if self._pageNumber > 1:
            # Header
            self.drawString(54, 750, "GATE CS 2027 — C PROGRAMMING QUESTION BANK")
            self.setStrokeColor(colors.HexColor("#CBD5E0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
            
            # Footer
            page_text = f"Page {self._pageNumber} of {page_count}"
            self.drawRightString(558, 40, page_text)
            self.drawString(54, 40, "Confidential — Generated by Antigravity IDE Engine")
            self.line(54, 52, 558, 52)
            
        self.restoreState()

class PDFExporter:
    def __init__(self, db_manager: DBManager):
        self.db_manager = db_manager

    def export_pdf(self, output_path="gate_c_programming_questions.pdf", limit=90):
        if not REPORTLAB_AVAILABLE:
            raise ImportError("reportlab package is required for PDF generation. Install it using 'uv pip install reportlab'.")

        questions = self.db_manager.get_questions(status="VALIDATED")
        if not questions:
            print("No validated questions found in the database. Generating layout with seed questions directly...")
            # If no validated in DB, get draft ones or seed ones to showcase output
            questions = self.db_manager.get_questions(status="DRAFT")
            if not questions:
                print("No questions at all. Cannot generate PDF.")
                return

        # If there is a massive database of questions, limit PDF size to keep compilation responsive
        if limit and len(questions) > limit:
            print(f"Limiting PDF generation to a balanced set of {limit} questions to ensure stability.")
            cat_limit = limit // 9
            subset = []
            difficulties = ["easy", "medium", "hard"]
            types = ["mcq", "msq", "nat"]
            for diff in difficulties:
                for q_type in types:
                    cat_qs = [q for q in questions if q["difficulty"].lower() == diff and q["type"].lower() == q_type]
                    subset.extend(cat_qs[:cat_limit])
            questions = subset

        # Setup doc
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )

        styles = getSampleStyleSheet()
        
        # Custom premium styles
        title_style = ParagraphStyle(
            'CoverTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=26,
            leading=32,
            textColor=colors.HexColor("#1A365D"),
            spaceAfter=15,
            alignment=1 # Center
        )
        
        subtitle_style = ParagraphStyle(
            'CoverSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#4A5568"),
            spaceAfter=30,
            alignment=1
        )
        
        section_heading = ParagraphStyle(
            'SectionHeading',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#2B6CB0"),
            spaceBefore=15,
            spaceAfter=15,
            keepWithNext=True
        )

        meta_badge_style = ParagraphStyle(
            'MetaBadge',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#2D3748")
        )

        body_style = ParagraphStyle(
            'QuestionBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2D3748"),
            spaceBefore=8,
            spaceAfter=8
        )

        code_style = ParagraphStyle(
            'CodeBlock',
            parent=styles['Normal'],
            fontName='Courier',
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1A202C"),
            backColor=colors.HexColor("#F7FAFC"),
            borderColor=colors.HexColor("#E2E8F0"),
            borderWidth=0.5,
            borderPadding=8,
            spaceBefore=8,
            spaceAfter=8
        )

        option_style = ParagraphStyle(
            'OptionText',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor("#2D3748"),
            spaceBefore=4,
            spaceAfter=4
        )

        explanation_style = ParagraphStyle(
            'ExplanationText',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14,
            textColor=colors.HexColor("#2D3748"),
            spaceBefore=6,
            spaceAfter=6
        )

        story = []

        # ================= COVER PAGE =================
        story.append(Spacer(1, 1.5 * inch))
        story.append(Paragraph("ANTIGRAVITY IDE ENGINE", subtitle_style))
        story.append(Paragraph("GATE CS 2027 ORIGINAL QUESTION BANK", title_style))
        story.append(Paragraph("SUBJECT: C PROGRAMMING", subtitle_style))
        story.append(Spacer(1, 0.5 * inch))
        
        # Build Stats Table for Cover
        stats_data = [
            ["Difficulty", "MCQ", "MSQ", "NAT", "Total"],
            ["Easy", "625", "625", "625", "1,875"],
            ["Medium", "625", "625", "625", "1,875"],
            ["Hard", "625", "625", "625", "1,875"],
            ["Total Target", "1,875", "1,875", "1,875", "5,625"]
        ]
        
        # Calculate actual stats from database
        easy_q = [q for q in questions if q["difficulty"].lower() == "easy"]
        med_q = [q for q in questions if q["difficulty"].lower() == "medium"]
        hard_q = [q for q in questions if q["difficulty"].lower() == "hard"]
        
        stats_actual = [
            ["Difficulty", "MCQ", "MSQ", "NAT", "Total (Actual in PDF)"],
            ["Easy", str(len([q for q in easy_q if q["type"].lower() == "mcq"])), 
             str(len([q for q in easy_q if q["type"].lower() == "msq"])), 
             str(len([q for q in easy_q if q["type"].lower() == "nat"])), 
             str(len(easy_q))],
            ["Medium", str(len([q for q in med_q if q["type"].lower() == "mcq"])), 
             str(len([q for q in med_q if q["type"].lower() == "msq"])), 
             str(len([q for q in med_q if q["type"].lower() == "nat"])), 
             str(len(med_q))],
            ["Hard", str(len([q for q in hard_q if q["type"].lower() == "mcq"])), 
             str(len([q for q in hard_q if q["type"].lower() == "msq"])), 
             str(len([q for q in hard_q if q["type"].lower() == "nat"])), 
             str(len(hard_q))],
            ["Total", str(len([q for q in questions if q["type"].lower() == "mcq"])), 
             str(len([q for q in questions if q["type"].lower() == "msq"])), 
             str(len([q for q in questions if q["type"].lower() == "nat"])), 
             str(len(questions))]
        ]
        
        t = Table(stats_actual, colWidths=[1.5*inch, 1.2*inch, 1.2*inch, 1.2*inch, 1.5*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1A365D")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 10),
            ('BOTTOMPADDING', (0,0), (-1,0), 8),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#F7FAFC")),
            ('TEXTCOLOR', (0,1), (-1,-1), colors.HexColor("#2D3748")),
            ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,1), (-1,-1), 9),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('ROWBACKGROUNDS', (0,1), (-1,-2), [colors.white, colors.HexColor("#EDF2F7")]),
            ('FONTNAME', (0,-1), (-1,-1), 'Helvetica-Bold'),
            ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor("#E2E8F0")),
        ]))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Compilation Summary (Validated Questions)", subtitle_style))
        story.append(t)
        story.append(PageBreak())

        # ================= SECTION 1: QUESTION BOOKLET =================
        story.append(Paragraph("SECTION 1: QUESTION BOOKLET", section_heading))
        story.append(Spacer(1, 0.1 * inch))

        for idx, q in enumerate(questions, 1):
            q_flowables = []
            
            # Format metadata banner
            meta_text = f"<b>Q{idx}</b> | ID: <b>{q['id']}</b> | Concept: <i>{q['concept']}</i> | Difficulty: <b>{q['difficulty'].upper()}</b> | Type: <b>{q['type'].upper()}</b>"
            meta_table = Table([[Paragraph(meta_text, meta_badge_style)]], colWidths=[doc.width])
            meta_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EDF2F7")),
                ('PADDING', (0,0), (-1,-1), 4),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('LINEBELOW', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E0")),
            ]))
            q_flowables.append(meta_table)
            q_flowables.append(Spacer(1, 0.05 * inch))
            
            # Process question text for C code blocks
            q_text = q["question"]
            parts = re.split(r'(```c.*?```)', q_text, flags=re.DOTALL)
            
            for part in parts:
                if part.startswith("```c"):
                    # Strip code block markers and leading/trailing whitespace
                    code_content = part.replace("```c", "").replace("```", "").strip()
                    # Keep code block formatted cleanly (preserve tabs/spaces as non-breaking spaces)
                    escaped_code = code_content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    escaped_code = escaped_code.replace(" ", "&nbsp;").replace("\n", "<br/>")
                    q_flowables.append(Paragraph(escaped_code, code_style))
                else:
                    escaped_text = part.replace("\n", "<br/>")
                    q_flowables.append(Paragraph(escaped_text, body_style))

            # Render options for MCQ/MSQ
            if q["options"]:
                opts = q["options"]
                opt_flowables = []
                for labels, opt_text in zip(["A", "B", "C", "D"], opts):
                    opt_html = f"<b>({labels})</b> {opt_text}"
                    opt_flowables.append(Paragraph(opt_html, option_style))
                
                # Check if options are short enough to display side-by-side (2x2 grid)
                max_len = max(len(opt) for opt in opts)
                if max_len < 30:
                    opt_table = Table([
                        [opt_flowables[0], opt_flowables[1]],
                        [opt_flowables[2], opt_flowables[3]]
                    ], colWidths=[doc.width/2.0, doc.width/2.0])
                else:
                    opt_table = Table([
                        [opt_flowables[0]],
                        [opt_flowables[1]],
                        [opt_flowables[2]],
                        [opt_flowables[3]]
                    ], colWidths=[doc.width])
                opt_table.setStyle(TableStyle([
                    ('PADDING', (0,0), (-1,-1), 2),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ]))
                q_flowables.append(opt_table)
                
            q_flowables.append(Spacer(1, 0.15 * inch))
            story.append(KeepTogether(q_flowables))

        story.append(PageBreak())

        # ================= SECTION 2: ANSWER KEY =================
        story.append(Paragraph("SECTION 2: ANSWER KEY", section_heading))
        story.append(Spacer(1, 0.15 * inch))

        # Build grid table of answers
        answer_rows = [["Question", "ID", "Type", "Correct Answer"]]
        for i, q in enumerate(questions, 1):
            ans = q["correct_answer"]
            # Formatting MSQ correct answer JSON
            if q["type"].lower() == "msq":
                try:
                    ans_list = json.loads(ans)
                    ans = ", ".join(ans_list)
                except Exception:
                    pass
            answer_rows.append([f"Q{i}", q["id"], q["type"].upper(), ans])
            
        ans_table = Table(answer_rows, colWidths=[1.0*inch, 2.0*inch, 1.2*inch, 2.0*inch])
        ans_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2B6CB0")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E0")),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#F7FAFC")]),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(ans_table)
        story.append(PageBreak())

        # ================= SECTION 3: SOLUTIONS =================
        story.append(Paragraph("SECTION 3: SOLUTIONS & EXPLANATIONS", section_heading))
        story.append(Spacer(1, 0.15 * inch))

        for idx, q in enumerate(questions, 1):
            sol_flowables = []
            
            # Format ID header
            sol_flowables.append(Paragraph(f"<b>Solution for Q{idx} ({q['id']})</b>", ParagraphStyle('SolHeader', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=11, leading=14, spaceBefore=8, spaceAfter=4, textColor=colors.HexColor("#2B6CB0"))))
            
            # Extract and format explanation text
            exp_text = q["explanation"].replace("\n", "<br/>")
            sol_flowables.append(Paragraph(exp_text, explanation_style))
            
            # Add line separator
            sol_flowables.append(Spacer(1, 0.05 * inch))
            line_table = Table([[""]], colWidths=[doc.width])
            line_table.setStyle(TableStyle([
                ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
                ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ]))
            sol_flowables.append(line_table)
            sol_flowables.append(Spacer(1, 0.1 * inch))
            
            story.append(KeepTogether(sol_flowables))

        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        print(f"PDF Question Bank successfully generated at: {output_path}")
